CREATE TABLE IF NOT EXISTS clients (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  FirstName TEXT NOT NULL,
  LastName TEXT NOT NULL,
  Pesel TEXT NOT NULL,
  Sex TEXT NOT NULL,
  DocumentType TEXT NOT NULL,
  DocumentNumber TEXT NOT NULL
);